version: '3'

volumes:
  prometheus-storage: {}
  grafana-storage: {}

services:
  main_service:
    build: .
    ports:
     - "8000:8000"
  prometheus:
    image: "prom/prometheus"
    volumes:
     - prometheus-storage:/prometheus
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    depends_on:
     - main_service
    ports:
     - "9090:9090"
  grafana:
    image: "grafana/grafana"
    env_file:
     - ./config/grafana.yml
    volumes:
     - grafana-storage:/var/lib/grafana
    depends_on:
     - prometheus
    links:
     - prometheus
    ports:
     - "3000:3000"
