version: '3'
services:
  prometheus:
    image: "prom/prometheus"
    volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - "9090:9090"
  grafana:
    image: "grafana/grafana"
    env_file:
      - ./config/grafana.yml
    depends_on:
     - prometheus
    links:
     - prometheus
    ports:
     - "3000:3000"
