#	Author: Indika Wijayasinghe
#	Email: i.b.wijayasinghe@ieee.org

global:
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape the bitcoin job every 15 seconds.
  - job_name: 'bitcoin_job'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8000']

