# A scrape configuration scraping a Node Exporter and the Prometheus server itself.
global:
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the my job every 5 seconds.
  - job_name: 'my_job'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']

